### ISSUE TITLE
Joe's review punchlist

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray.dev#18]
This is a rundown of my review of the current homepage draft. It's looking great!

- [ ] header logo is too small. We probably need to remake the logo wordmark for this. One idea would be to put a larger logo below at the top of the page (where **xarray** is now). Perhaps reworking the top a bit to include: 
  - Logo
  - Subtitle: "Xarray provides N-D labeled arrays and datasets in Python"
  - (remove the intro text)
- [ ] the youtube video of @shoyer is great but its 6 years old! I'm sure we can do better (maybe @rabernat has something) (or as @TomNicholas suggested, just record a new video)
- [x] ~(formerly **xray**)~ I think we can stop highlighting this point now.
- [x] I'd prefer to capitalize Xarray when referring to the project (not the package import).
- [ ] Under "Key Features & Capabilities": 
   - [x] Replace Lorem ipsum with "Xarray provides data models for working with labeled arrays and datasets. It's toolkit includes a broad set of domain-agnostic functions for advanced analytics and visualization with these data structures."
   - [x] Under Interoperability: "Interoperable with the scientific Python ecosystem including NumPy, Dask, Pandas, and Matplotlib."
   - [ ] add syntax highlighting for code samples
   - [x] Under "Flexible and Extensible I/O backend API": "Read and write data to and from NetCDF, HDF, Zarr, OpenDAP, and GRIB"
 - [x] Under ecosystem:
   - [x] replace lorem ipsum with: "Xarray is part of the larger scientific Python ecosystem. Its built on top of NumPy, Pandas, and Dask and supports a wide range of domain specific scientific applications." 
   - [x] array libraries: replace lorem ipsum with "Xarray's supports multiple array backends, allowing users to choose array types that work best for their application."
   - [x] logos feel a little small (especially compared to the size of the logos in the next sections)
   - [x] scientific domains - this section is a bit bland. Perhaps we can spice it up a bit. Ideas? Show logos? GitHub stars? Links to packages?
- [x] Supported By: Logo's too big?
- [x] Donate: Logo too big? Also, let's make sure we get a link to numfocus's donate page. Ahhhhh, just found it under the logo. Let's move the donate button to the right (with the text).
- [x] twitter/github button's at bottom are too small.
- [x] #21
- [ ] I like the header. Can we get this on our sphinx page too?

**Comment by andersy005** [comment]
@TomNicholas, @jhamman, thank you for your feedback! I'm going to make adjustments tomorrow and will ping you for another round of review...

**Comment by andersy005** [comment]
@jhamman, I addressed a few items in #20 


> header logo is too small. We probably need to remake the logo wordmark for this. 

> the youtube video of @shoyer is great but its 6 years old! I'm sure we can do better (maybe @rabernat has something) (or as @TomNicholas suggested, just record a new video)

👍🏽  I increased the header logo size and removed the outdated/old video and replaced it with @TomNicholas image suggestion in https://github.com/andersy005/xarray-website/issues/18#issuecomment-910567877 for the time being... Let me know if you still think it's worth to implement this:

> One idea would be to put a larger logo below at the top of the page (where xarray is now)

---

> add syntax highlighting for code samples

Getting this to work turned out to be more involved than I expected... I made slight changes (they are not perfect but I think they are good enough for the time being). 

> scientific domains - this section is a bit bland. Perhaps we can spice it up a bit. Ideas? Show logos? GitHub stars? Links to packages?

👍🏽 I will try to address this as part of #15

> Also we could make a better list of projects to display there which shows more scientific diversity - we don't need to have half the examples all be "Geoscience". (We can also subdivide geoscience into oceanography, meterology, etc. I reckon)

I could use some help with coming up with a diverse list of projects to highlight.
