### ISSUE TITLE
Broken page for some reason

### ISSUE THREAD

**Issue by TomNicholas** [xarray-contrib/xarray.dev#264]
This just happened @andersy005 :/

I can interrogate the console if you need, but I'm pretty ignorant of what it means

![Screenshot from 2022-07-16 09-08-32](https://user-images.githubusercontent.com/35968931/179358317-85052fd2-bd7f-495d-9a8e-e087bef570fc.png)

**Comment by TomNicholas** [comment]
I posted the problem in the scipy slack for help by the way too

https://scipy2022.slack.com/archives/C03L0AHTJUB/p1657981890619899

https://scipy2022.slack.com/archives/C03LQ5GBRR6/p1657981799055069

**Comment by andersy005** [comment]
Thank you for the report, @TomNicholas! Your IP address may have reached GitHub's API rate limit. When you follow that first link in the console ( `api.github.com/...`) in a new tab, do you get any detailed error message ?

**Comment by TomNicholas** [comment]
`{"message":"API rate limit exceeded for 12.231.120.253. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

Others were able to reproduce the error though

**Comment by andersy005** [comment]
Okay. It looks like what I expected. I'm going to switch to authenticated api requests on behalf of users. I should have a fix for this shortly

**Comment by jsignell** [comment]
I was wondering if you might want to implement some caching rather than computing stats on the fly.

**Comment by jsignell** [comment]
It would probably not be too rough to have a github action that runs on a schedule and does the fetch and puts it somewhere where the website can access it

**Comment by andersy005** [comment]
> It would probably not be too rough to have a github action that runs on a schedule and does the fetch and puts it somewhere where the website can access it

currently, there's a [datasette](https://github.com/simonw/datasette) instance running heroku: https://pydata-datasette.herokuapp.com/xarray. this instance hosts data that are updated on a daily frequency. i've switched to using this in #265

**Comment by andersy005** [comment]
@TomNicholas, the client error should be fixed. let me know if you are still experiencing it

**Comment by TomNicholas** [comment]
@andersy005 I think that fixed it! Thank you so much! :1st_place_medal:

**Comment by jsignell** [comment]
> > It would probably not be too rough to have a github action that runs on a schedule and does the fetch and puts it somewhere where the website can access it
> 
> currently, there's a [datasette](https://github.com/simonw/datasette) instance running on heroku: https://pydata-datasette.herokuapp.com/xarray. this instance hosts data that are updated on a daily frequency. i've switched to using this in #265

Well that is way smarter :) yay!
