### ISSUE TITLE
On mobile, nav links scroll the nav

### ISSUE THREAD

**Issue by zmoon** [xarray-contrib/xarray.dev#317]
Tested on my Android phone on both Chrome and Firefox.

If you are jumping up in the page, this is fine, but if you are going down, this scrolling puts the hamburger close button out of screen, making it a bit hard/annoying to get out of the nav.

<details><summary>Screenshot</summary>

![Screenshot_2022-08-29-16-04-38-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/15079414/187307319-e721ea49-46c6-4885-b7f3-968c9841ee4f.jpg)
</details>

**Comment by zmoon** [comment]
Does seem better in #316

**Comment by andersy005** [comment]
thank you for reporting this, @zmoon! i just merged #316, can you confirm that this is not an issue anymore? i tested this on ios and everything seems to be working fine.

**Comment by zmoon** [comment]
Yep seems good!

**Comment by andersy005** [comment]
Awesome! thank you 🙏
