### ISSUE TITLE
[User story proposal] Xarray for Bayesian modeling (PyMC, ArviZ)

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray.dev#348]
This is a proposal for a bayesian modeling use case story for Xarray. The story will be published on Xarray's blog (https://xarray.dev/blog). 

### Why?

Xarray is used as the underlying data structure in ArviZ (and PyMC?) today. A user story blog post showing how Xarray is used used to represent and analyze bayesian model data would help socialize the concept across the Xarray developer and broader Bayesian modeling communities. 

### What?

We are targeting a short and non-technical post that illustrates how Xarray is used in the ArviZ context. Below is a template outline that you should feel free to modify:

1. Who am I?
2. What problem am I trying to solve?
3. How does Xarray help?
4. Why did I choose Xarray? 
5. Current pain points (or ways that Xarray could better serve your use case)
6. Technology I use around Xarray
7. Anything else to know?
8. Links and references

Feel free to insert images or short code blocks if they help you tell your story.

### How?

Xarray's blog using Markdown with some front-matter. You can copy one of the [existing posts](https://github.com/xarray-contrib/xarray.dev/tree/main/src/posts) to get started or you can write in a google-doc-like-thing and ask us to do the markdown formatting. If you copy a previous post, use a name like `user-story-arviz` or whatever makes sense for your application.

xref: https://github.com/xarray-contrib/xarray.dev/issues/272

**Comment by jhamman** [comment]
@OriolAbril and/or @canyon289 - would either (or both) of you be up for contributing a blog post here?

**Comment by jhamman** [comment]
@canyon289 - Circling back here. Are you still up for writing a post? We're ready to help get it on the site whenever you are ready.

**Comment by canyon289** [comment]
@jhamman dont want to lose track of this. Should I just copy the template from say this post and make a PR?

https://github.com/xarray-contrib/xarray.dev/tree/main/src/posts/introducing-pint-xarray

**Comment by jhamman** [comment]
@canyon289 - that would be great!

**Comment by canyon289** [comment]
@jhamman Sorry for the delay. I am actively working on this. looking to get you a draft in the next week

https://github.com/canyon289/xarray.dev/blob/inf_data/src/posts/introducing-inference-data/index.md
