### ISSUE TITLE
Accommodate team member website URL without scheme?

### ISSUE THREAD

**Issue by zmoon** [xarray-contrib/xarray.dev#370]
@andersy005 , on <https://xarray.dev/team>, your website link is set incorrectly as  `https://xarray.dev/blog.andersonbanihirwe.dev` currently. Cool team page though. It looks like the ones that work correctly have the scheme included in their URL on their GitHub, whereas your GitHub does not.

**Comment by andersy005** [comment]
thank you for reporting this, @zmoon! The issue should be resolved by now.
