### ISSUE TITLE
Xarray for radar analysis

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray.dev#389]
This is a proposal for a radar data analysis use case story for Xarray. The story will be published on Xarray's blog (https://xarray.dev/blog). 

### Why?

One or more user stories that highlight how Xarray is used for radar data analysis would help show Xarray's impact in this area. Ideally we show how Xarray is used with radar data in operations and for basic research, as well as how it is used in the cloud and on HPCs.

### What?

We are targeting a short and non-technical post that illustrates how Xarray is used in the climate context. Below is a template outline that you should feel free to modify:

1. Who am I?
2. What problem am I trying to solve?
3. How does Xarray help?
4. Why did I choose Xarray? 
5. Current pain points (or ways that Xarray could better serve your use case)
6. Technology I use around Xarray
7. Anything else to know?
8. Links and references

Feel free to insert images or short code blocks if they help you tell your story.

### How?

Xarray's blog using Markdown with some front-matter. You can copy one of the [existing posts](https://github.com/xarray-contrib/xarray.dev/tree/main/src/posts) to get started or you can write in a google-doc-like-thing and ask us to do the markdown formatting. If you copy a previous post, use a name like `user-story-pangeo-ocean-model` or whatever makes sense for your application.

xref: https://github.com/xarray-contrib/xarray.dev/issues/272

**Comment by dcherian** [comment]
cc @mgrover1 @kmuehlbauer

**Comment by mgrover1** [comment]
Yes! Let's do it :)

**Comment by kmuehlbauer** [comment]
@mgrover1 I've forked this to openradar and set up a minimal blog post https://github.com/openradar/xarray.dev/tree/radar-blog-post. Please feel free to add/adapt/change as needed.

**Comment by mgrover1** [comment]
@kmuehlbauer I am thinking we could make it a bit more generic... with a timeline and look at different data models, and why Xarray and it's recent developments make it well suited.

**Comment by kmuehlbauer** [comment]
> @kmuehlbauer I am thinking we could make it a bit more generic... with a timeline and look at different data models, and why Xarray and it's recent developments make it well suited.

Yes, sure, this was just a first serve. Use as much as you think is useful of the current content. We could iterate on the fork in issues, if needed.

**Comment by dcherian** [comment]
@mgrover1 your proposal sounds like exciting reading :) It would also be good to hear what the pain points are.

**Comment by mgrover1** [comment]
@dcherian - we have drafted up a document. I invited you as a collaborator on the HackMD. Once that is good shape, we can open a PR and get this into review.

**Comment by dcherian** [comment]
Sorry for the delay

This looks great to me. Open a PR!
