### ISSUE TITLE
core maintainers not showing

### ISSUE THREAD

**Issue by ntabris** [xarray-contrib/xarray.dev#418]
When I go to https://xarray.dev/team, I see this:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/46289310/211406745-659e3d2c-780f-4f37-b019-36af770f8600.png">

(I see this in Safari and Chrome)

**Comment by andersy005** [comment]
@ntabris, thank you for reporting this. As it turns out, the issue was caused by expired credentials. The problem should now be resolved
