### ISSUE TITLE
Broken image in "Unit-aware arithmetic in Xarray, via pint" post

### ISSUE THREAD

**Issue by VeckoTheGecko** [xarray-contrib/xarray.dev#535]
https://xarray.dev/blog/introducing-pint-xarray

https://github.com/xarray-contrib/xarray.dev/blob/b146534a481d68c571f40674b480d6e9512e2728/src/posts/introducing-pint-xarray/index.md?plain=1#L39

https://web.archive.org/web/20191116161743/https://clqtg10snjb14i85u49wifbv-wpengine.netdna-ssl.com/wp-content/uploads/2017/12/Customers.jpg

I couldn't find an alternative link that seemed durable.

cc @TomNicholas (the original author)

**Comment by andersy005** [comment]
thank you for reporting this, @VeckoTheGecko
