### ISSUE TITLE
Add RSS feed / button

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray.dev#550]
### Is your feature request related to a problem?
A easy way to subscribe to news from xarray blog

### Describe the solution you'd like
A support for publishing news and button to subscribe to rss from blog (along twitter icon etcera)

Originally requested by @danieltomasz here: https://github.com/pydata/xarray/issues/7805

**Comment by andersy005** [comment]
@danieltomasz, 

Thank you for taking time to request this feature! The RSS feed feature has been implemented and it resides here: https://xarray.dev/atom.xml

<img width="355" alt="Screenshot 2023-06-21 at 20 53 08" src="https://github.com/xarray-contrib/xarray.dev/assets/13301940/0d63b0cb-42d1-45e3-a8db-c7ca21e41cbd">
