### ISSUE TITLE
Markdown not rendering correctly on blog posts

### ISSUE THREAD

**Issue by TomNicholas** [xarray-contrib/xarray.dev#660]
The blog posts on our site don't seem to be rendering markdown correctly anymore. This screenshot of the [kvikio post](https://xarray.dev/blog/cupy-tutorial) should have subsection headings and paragraph breaks.

<img width="1018" alt="Screenshot 2024-02-09 at 1 11 55 PM" src="https://github.com/xarray-contrib/xarray.dev/assets/35968931/92da7603-1fe2-499f-9e5b-367af2256106">

This seems to be happening on all the blog posts.

**Comment by andersy005** [comment]
thank you for spotting this, @TomNicholas! this is mostly likely caused by a dependency update. i'm going to look into it
