### ISSUE TITLE
plan for integration with xarray's sphinx site

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray.dev#89]
Now that we are close to launching this site, we should make a plan for how to integrate it with the existing sphinx documentation site and related content. 

Based on the xarray dev-team call this morning, I think this is our working plan

1. Deploy this project to [xarray.dev](https://xarray.dev)
2. Using Vercel's configurable routing, rewrite https://xray.readthedocs.io/ to xarray.dev
3. Once (1) and (2) are working, redirect http://xarray.pydata.org/ to https://xarray.dev

**Comment by andersy005** [comment]
@jhamman, should I transfer this repository to xarray-contrib or xarray-dev? Thought it would make it easy to grant you and/or someone else access to both the Github repository and the Vercel account once the repository resides under a GitHub org.

**Comment by jhamman** [comment]
I now have this site live at https://xarray.dev and the docs are live at https://docs.xarray.dev (though readthedocs is still redirecting to the xarray.pydata.org url)

**Comment by andersy005** [comment]
> I now have this site live at [xarray.dev](https://xarray.dev) and the docs are live at [docs.xarray.dev](https://docs.xarray.dev) (though readthedocs is still redirecting to the xarray.pydata.org url)

Sweet 🎉

**Comment by andersy005** [comment]
update: we're still waiting on Pydata folks to help us adjust DNS settings to redirect subpaths of `xarray.pydata.org` to `docs.xarray.dev`. e.g.: https://xarray.pydata.org/en/stable/examples/monthly-means.html should redirect to https://docs.xarray.dev/en/stable/examples/monthly-means.html

**Comment by jhamman** [comment]
NumFOCUS and Pydata have done what they can. I'm now working with the folks at readthedocs to enable a force redirect feature.

For later reference, our desired readthedocs domain/redirect configs are: 

```
DOMAIN SETTING
--------------
Canonical: [docs.xarray.dev](http://docs.xarray.dev/)
REDIRECT SETTING
----------------
Type: Exact Redirect
From URL: /$rest
To URL: https://docs.xarray.dev/
Force Redirect: True
```

This config currently results in successfuly redirect to the new domain but at the cost of the site CSS failing to load: 
![image](https://user-images.githubusercontent.com/2443309/181836050-e72b9fce-de62-498a-b7d6-a736c49bc10e.png)

I've asked readthedocs for more help and will report back.

**Comment by jhamman** [comment]
The folks at Read the Docs pushed a fix today that solves the issue above. I've reinstated our redirect and everything appears normal. I'll close this now but folks should chime in if they notice any issues.
